controller_manager:
  ros__parameters:
    update_rate: 2  # Hz
    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController
      


forward_command_controller_position:
  ros__parameters:
    joints: 
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    interface_name: position


      
